<div style="font-size:22pt; line-height:25pt; font-weight:bold; text-align:center;">Differential evolution algorithm</div>

1. [Introduction](#int)
2. [L'algorithme DE](#de)
    1. [Pseudo-code](#pseudo)
    2. [DE python code](#code)
3. [Test](#de)    
6. [References](#ref)


# <a id="data"></a> Introduction

Besides particle swarm optimization (PSO) which I touched on previously, differential evolution (DE) is one of my go-to favorites. Just like PSO, differential evolution falls within the evolutionary algorithms (EA) family. Differential evolution is very similar to genetic algorithms (GA) which are based on the principles of evolutionary biology such as mutation, crossover, and selection.

Differential evolution is basically a genetic algorithm that natively supports float value based cost functions.

<div class="alert alert-success">
<b>Hypothèses:</b>
<ul>
<li>
    
</li>

<li>
    
</li>
</ul>
</div>

<div class="alert alert-warning">
<b>Limitations:</b>
<ul>
<li>
    
</li>

<li>
    
</li>
</ul>
</div>


# <a id="de"></a> L'algorithme DE

## <a id="pseudo"></a> Pseudo-code

1) Initialize a random population of individuals throughout the search space.

2) while iter <= max num of generations

    3) cycle through each individual in the population
    
        3.A) perform mutation
            
        3.B) perform recombination ("crossover" in GA lingo)
            
        3.C) perform selection
            
    4) if stopping criterion has been met:
            exit and return best individual
            
        else:
            iter = iter + 1
            go back to step #3


In [14]:
import numpy as np

def de(fobj, bounds, mut=0.8, crossp=0.7, popsize=20, its=1000):
    dimensions = len(bounds)
    pop = np.random.rand(popsize, dimensions)
    min_b, max_b = np.asarray(bounds).T
    diff = np.fabs(min_b - max_b)
    pop_denorm = min_b + pop * diff
    fitness = np.asarray([fobj(ind) for ind in pop_denorm])
    best_idx = np.argmin(fitness)
    best = pop_denorm[best_idx]
    for i in range(its):
        for j in range(popsize):
            idxs = [idx for idx in range(popsize) if idx != j]
            a, b, c = pop[np.random.choice(idxs, 3, replace = False)]
            mutant = np.clip(a + mut * (b - c), 0, 1)
            cross_points = np.random.rand(dimensions) < crossp
            if not np.any(cross_points):
                cross_points[np.random.randint(0, dimensions)] = True
            trial = np.where(cross_points, mutant, pop[j])
            trial_denorm = min_b + trial * diff
            f = fobj(trial_denorm)
            if f < fitness[j]:
                fitness[j] = f
                pop[j] = trial
                if f < fitness[best_idx]:
                    best_idx = j
                    best = trial_denorm
        yield best, fitness[best_idx]

# <a id="test"></a> Test

In [26]:
fobj = lambda x: sum(x**2)/len(x)

it = list(de(lambda x: x**2, bounds=[(-100, 100)]))
print(it[-1])

(array([0.]), array([0.]))


In [48]:
result = list(de(rosen, bounds, its=5000))
print(result[-1])

(array([1., 1., 1., 1., 1.]), 0.0)


# <a id="comp"></a> Comparaison PYTHON


In [39]:
from scipy.optimize import rosen, differential_evolution

bounds = [(0,2), (0, 2), (0, 2), (0, 2), (0, 2)]


In [36]:
%time
result = differential_evolution(rosen, bounds)
result.x, result.fun

CPU times: user 3 µs, sys: 0 ns, total: 3 µs
Wall time: 6.68 µs


(array([1., 1., 1., 1., 1.]), 0.0)

In [22]:
# demo.py

from differential_evolution import DifferentialEvolution
import datetime

import numpy as np
from matplotlib import pyplot as plt

if __name__ == '__main__':
    number_of_runs = 5
    val = 0
    print_time = True

    for i in xrange(number_of_runs):
        start = datetime.datetime.now()
        de = DifferentialEvolution(num_iterations=200, dim=10, CR=0.4, F=0.48, population_size=75, print_status=False, func='sphere')
        val += de.simulate()
        if print_time:
            print('\nTime taken:', datetime.datetime.now() - start)
    print('-'*80)
    print("\nFinal average of all runs:", val / number_of_runs)

NameError: name 'demo' is not defined

# <a id="data"></a> References

Useful imports and configuration: